# Generated by Django 5.2.5 on 2025-09-12 09:28

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_images_delete_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[utils.validators.validate_no_special_symbols]),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, null=True, validators=[utils.validators.validate_array_of_urls]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, validators=[utils.validators.validate_no_special_symbols]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=255, unique=True, validators=[utils.validators.validate_no_special_symbols]),
        ),
    ]
