# Generated by Django 5.2.5 on 2025-09-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_description_alter_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='og_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dis_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dis_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
