# Generated by Django 5.2.5 on 2025-09-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_discountrule_productattribute_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='discount_rule',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='inventory',
        ),
        migrations.AlterUniqueTogether(
            name='productdiscount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='BulkPricingTier',
        ),
        migrations.DeleteModel(
            name='DiscountRule',
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.DeleteModel(
            name='ProductDiscount',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
