"""add colors and product variant color relation

Revision ID: 8a2829eaead7
Revises: 692cc5eb4c4b
Create Date: 2026-04-28 00:49:02.801869

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8a2829eaead7'
down_revision = '692cc5eb4c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sizes_product_id'), 'sizes', ['product_id'], unique=False)
    op.create_table('colors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hex_value', sa.String(length=7), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_product_id'), 'colors', ['product_id'], unique=False)
    op.add_column('product_variants', sa.Column('color_id', sa.UUID(), nullable=True))
    op.add_column('product_variants', sa.Column('size_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'product_variants', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_variants', 'colors', ['color_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_column('product_variants', 'size_id')
    op.drop_column('product_variants', 'color_id')
    op.drop_index(op.f('ix_colors_product_id'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('ix_sizes_product_id'), table_name='sizes')
    op.drop_table('sizes')
    # ### end Alembic commands ###