"""add color and size to product variants

Revision ID: 69cb41a74d11
Revises: cd59b45baa8f
Create Date: 2026-04-26 23:44:47.205069

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '69cb41a74d11'
down_revision = 'cd59b45baa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('color', sa.String(), nullable=True))
    op.add_column('product_variants', sa.Column('size', sa.String(length=3), nullable=True))
    op.drop_column('product_variants', 'weight_grams')
    op.drop_column('product_variants', 'length_mm')
    op.drop_column('product_variants', 'height_mm')
    op.drop_column('product_variants', 'width_mm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('width_mm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('height_mm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('length_mm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('weight_grams', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product_variants', 'size')
    op.drop_column('product_variants', 'color')
    # ### end Alembic commands ###