"""create color and size table and add foreign key to product variant

Revision ID: 692cc5eb4c4b
Revises: c6c38e0900e6
Create Date: 2026-04-28 00:41:46.209416

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '692cc5eb4c4b'
down_revision = 'c6c38e0900e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'color')
    op.drop_column('product_variants', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('size', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('color', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###