# Generated by Django 5.2.5 on 2025-09-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_session_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
